// Package orders provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package orders

// CreateOrder defines model for CreateOrder.
type CreateOrder struct {
	DeliveryAddress string      `json:"deliveryAddress"`
	OrderItems      []OrderItem `json:"orderItems"`
	ReceiverName    string      `json:"receiverName"`
	UserUUID        string      `json:"userUUID"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Quantity int    `json:"quantity"`
	SkuID    string `json:"skuID"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrder
