openapi: "3.0.0"
info:
  version: 1.0.0
  title: EDA order
  description: TODO
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost

paths:
  /orders:
    post:
      operationId: createOrder
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrder'
      responses:
        '200':
          description: todo
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CreateOrder:
      type: object
      required: [orderItems, userUUID, receiverName, deliveryAddress]
      properties:
        userUUID:
          type: string
        receiverName:
          type: string
        deliveryAddress:
          type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      required: [skuID, quantity]
      properties:
        skuID:
          type: string
        quantity:
          type: integer
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
